#!/usr/bin/env node
/**
 * Compile presets/<domain>/*.md from the repo root into typed
 * TypeScript modules under src/<domain>/index.ts. Each
 * generated module exports:
 *
 *   - One named export per preset, camelCased from its `name` slug
 *     (e.g. `user-asked-about-an-incident` → `userAskedAboutAnIncident`).
 *   - A `<DOMAIN>_PRESETS` array containing every preset in that
 *     domain, in filesystem order (alphabetical by filename).
 *
 * Validation, all fatal:
 *
 *   - Frontmatter must have a non-empty `name` and `description`.
 *   - The frontmatter `name` must match the filename (without `.md`).
 *   - Names must be unique within a domain folder.
 *   - Every ```yaml block in the body must parse as valid YAML.
 *
 * Run before `tsc`. Authored markdown lives at the repo root in
 * `presets/<domain>/<name>.md`; the build is the only consumer.
 */

import { readdir, readFile, mkdir, writeFile, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, join, basename, extname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import YAML from 'yaml';

const __filename = fileURLToPath(import.meta.url);
const PACKAGE_ROOT = resolve(__filename, '..', '..');
const REPO_ROOT = resolve(PACKAGE_ROOT, '..', '..');
const PRESETS_DIR = join(REPO_ROOT, 'presets');
const SRC_DIR = join(PACKAGE_ROOT, 'src');
/**
 * Domain directories the compile step is allowed to overwrite/clean.
 * Anything else under src/ (notably index.ts, but also any future
 * hand-written file) is left alone.
 */
const KNOWN_GENERATED_BARREL = join(SRC_DIR, 'index.ts');

const errors = [];
function fail(file, message) {
  errors.push(`  ${relative(REPO_ROOT, file)}: ${message}`);
}

function camelCase(slug) {
  return slug
    .split('-')
    .map((part, i) => (i === 0 ? part : part[0].toUpperCase() + part.slice(1)))
    .join('');
}

function constantCase(slug) {
  return slug.toUpperCase().replace(/-/g, '_');
}

/**
 * Validate every ```yaml ... ``` fenced block in a markdown body parses.
 * Returns an array of error messages (empty if all blocks are valid).
 */
function validateYamlBlocks(body) {
  const fence = /^```yaml\s*\n([\s\S]*?)\n```/gm;
  const issues = [];
  let match;
  let blockIndex = 0;
  while ((match = fence.exec(body)) !== null) {
    blockIndex++;
    const yamlText = match[1];
    try {
      YAML.parse(yamlText);
    } catch (err) {
      issues.push(`yaml block #${blockIndex}: ${err.message}`);
    }
  }
  return issues;
}

async function compileDomain(domainDir, domainName) {
  const entries = await readdir(domainDir, { withFileTypes: true });
  const files = entries
    .filter((e) => e.isFile() && extname(e.name) === '.md')
    .map((e) => e.name)
    .sort();

  if (files.length === 0) {
    console.warn(`[mcp-presets] domain "${domainName}" is empty; skipping`);
    return null;
  }

  const seenNames = new Set();
  const presets = [];

  for (const filename of files) {
    const file = join(domainDir, filename);
    const raw = await readFile(file, 'utf8');
    const parsed = matter(raw);
    const fm = parsed.data;
    const body = parsed.content;

    if (typeof fm.name !== 'string' || fm.name.trim() === '') {
      fail(file, 'frontmatter `name` is required (non-empty string).');
      continue;
    }
    if (typeof fm.description !== 'string' || fm.description.trim() === '') {
      fail(file, 'frontmatter `description` is required (non-empty string).');
      continue;
    }

    const expectedName = basename(filename, '.md');
    if (fm.name !== expectedName) {
      fail(
        file,
        `frontmatter \`name\` ("${fm.name}") must match the filename ("${expectedName}").`,
      );
      continue;
    }

    if (seenNames.has(fm.name)) {
      fail(file, `duplicate name "${fm.name}" within domain "${domainName}".`);
      continue;
    }
    seenNames.add(fm.name);

    for (const issue of validateYamlBlocks(body)) {
      fail(file, issue);
    }

    presets.push({
      filename,
      name: fm.name,
      description: fm.description,
      body,
    });
  }

  return { domainName, presets };
}

function emitTs(domain) {
  const lines = [];
  lines.push(`// AUTO-GENERATED by scripts/compile-presets.mjs — do not edit.`);
  lines.push(
    `// Source markdown lives at /presets/${domain.domainName}/*.md.`,
  );
  lines.push(`import type { LensPreset } from '@mcp-lens/sdk';`);
  lines.push('');

  for (const preset of domain.presets) {
    const ident = camelCase(preset.name);
    lines.push(`/**`);
    lines.push(` * ${preset.description.replace(/\*\//g, '*\\/')}`);
    lines.push(` *`);
    lines.push(` * Source: presets/${domain.domainName}/${preset.filename}`);
    lines.push(` */`);
    // Use a JSON-encoded string for `description` and `body` to avoid
    // template-literal escaping headaches with backticks/${}.
    lines.push(`export const ${ident}: LensPreset = {`);
    lines.push(`  name: ${JSON.stringify(preset.name)},`);
    lines.push(`  description: ${JSON.stringify(preset.description)},`);
    lines.push(`  body: ${JSON.stringify(preset.body)},`);
    lines.push(`};`);
    lines.push('');
  }

  const arrayName = `${constantCase(domain.domainName)}_PRESETS`;
  lines.push(`/**`);
  lines.push(` * Every preset in the "${domain.domainName}" domain, in`);
  lines.push(` * filesystem order. Convenient for one-line consumption:`);
  lines.push(` *`);
  lines.push(`*    registerPresets(server, ${arrayName});`);
  lines.push(` */`);
  lines.push(`export const ${arrayName}: LensPreset[] = [`);
  for (const preset of domain.presets) {
    lines.push(`  ${camelCase(preset.name)},`);
  }
  lines.push(`];`);
  lines.push('');

  return lines.join('\n');
}

async function main() {
  if (!existsSync(PRESETS_DIR)) {
    console.error(`[mcp-presets] presets directory not found: ${PRESETS_DIR}`);
    process.exit(1);
  }

  await mkdir(SRC_DIR, { recursive: true });

  const domainEntries = await readdir(PRESETS_DIR, { withFileTypes: true });
  const domainDirs = domainEntries
    .filter((e) => e.isDirectory() && !e.name.startsWith('.'))
    .map((e) => e.name)
    .sort();

  const compiled = [];
  for (const domainName of domainDirs) {
    const result = await compileDomain(
      join(PRESETS_DIR, domainName),
      domainName,
    );
    if (result) compiled.push(result);
  }

  if (errors.length > 0) {
    console.error('[mcp-presets] compile failed:');
    for (const e of errors) console.error(e);
    process.exit(1);
  }

  // Reset known domain folders, write per-domain modules.
  const compiledDomainNames = new Set(compiled.map((d) => d.domainName));
  // Clean any pre-existing generated domain folder (so a renamed/removed
  // domain doesn't linger across builds).
  const existingSrc = await readdir(SRC_DIR, { withFileTypes: true }).catch(
    () => [],
  );
  for (const e of existingSrc) {
    if (e.isDirectory() && !e.name.startsWith('.')) {
      // Only purge folders we own (i.e. ones that look generated).
      // We mark every emitted file with the AUTO-GENERATED header; if
      // a file under src/<domain>/ ever ships hand-written, this script
      // won't clobber it because the cleanup is folder-targeted not
      // file-targeted.
      await rm(join(SRC_DIR, e.name), { recursive: true, force: true });
    }
  }
  for (const domain of compiled) {
    const domainOut = join(SRC_DIR, domain.domainName);
    await mkdir(domainOut, { recursive: true });
    await writeFile(join(domainOut, 'index.ts'), emitTs(domain), 'utf8');
  }

  // Write the top-level barrel that re-exports each domain under its slug.
  const topLines = [
    `// AUTO-GENERATED by scripts/compile-presets.mjs — do not edit.`,
    `// Per-domain barrel.`,
    '',
  ];
  for (const domain of compiled) {
    topLines.push(
      `export * as ${camelCase(domain.domainName)} from './${domain.domainName}/index.js';`,
    );
  }
  topLines.push('');
  await writeFile(KNOWN_GENERATED_BARREL, topLines.join('\n'), 'utf8');

  const totalPresets = compiled.reduce((n, d) => n + d.presets.length, 0);
  console.log(
    `[mcp-presets] compiled ${totalPresets} preset(s) across ${compiled.length} domain(s):`,
  );
  for (const d of compiled) {
    console.log(`  ${d.domainName}: ${d.presets.length} preset(s)`);
  }
}

main().catch((err) => {
  console.error('[mcp-presets] unexpected failure:', err);
  process.exit(1);
});
